name: Build
on: push

env:
  OPTIMIZE_MODES: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]

jobs:
  define-matrix:
    runs-on: ubuntu-24.04-arm
    outputs:
      include: ${{ steps.include.outputs.include }}
    steps:
      - name: Define include
        id: include
        run: |
          echo "include=$(yq -n -oj -I0 '
            [
              { "arch": "x86", "platform": "windows-msvc" },
              { "arch": "wasm32", "platform": "wasi" }
            ] as $bases |
            env(OPTIMIZE_MODES) as $optimizations |
            [
              $bases[] as $b |
              $optimizations[] as $o |
              $b + { "optimize": $o }
            ]
          ')" >> "$GITHUB_OUTPUT"
  build:
    runs-on: macos-latest
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
        platform: [linux-musl, windows-msvc, macos, freebsd, netbsd]
        optimize: ${{ env.OPTIMIZE_MODES }}
        include: ${{ fromJSON(needs.define-matrix.outputs.include) }}
    env:
      XWIN_SDK_VERSION: 10.0.22621
      VCLTL_VERSION: 5.2.2
      VCLTL_TARGET_VERSION: 10.0.19041.0
      XCODE_VERSION: 26.0.1
      MACOS_SDK_VERSION: 26.0
      TARGET_ARCH: ${{ matrix.arch }}
      TARGET_PLATFORM: ${{ matrix.platform }}
      TARGET_TRIPLE: ${{ matrix.arch }}-${{ matrix.platform }}
      OPTIMIZE_MODE: ${{ matrix.optimize }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup zig
        uses: mlugg/setup-zig@v2

      - name: Install xwin
        if: ${{ matrix.platform == 'windows-msvc' }}
        run: |
          brew update
          brew install xwin

      - name: Build and pack
        run: ./.github/workflows/build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TARGET_TRIPLE }}-${{ matrix.optimize }}
          path: gnuplot-${{ env.TARGET_TRIPLE }}.*
          if-no-files-found: error
