name: Build
on: push
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
        platform: [linux-musl, windows-msvc, macos, freebsd, netbsd]
        optimize: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]
        include:
          - arch: x86
            platform: windows-msvc
            optimize: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]
          - arch: wasm32
            platform: wasi
            optimize: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]
    runs-on: macos-latest
    env:
      XWIN_SDK_VERSION: 10.0.22621
      VCLTL_VERSION: 5.2.2
      VCLTL_TARGET_VERSION: 10.0.19041.0
      XCODE_VERSION: 26.0.1
      MACOS_SDK_VERSION: 26.0
      TARGET_ARCH: ${{ matrix.arch }}
      TARGET_PLATFORM: ${{ matrix.platform }}
      TARGET_TRIPLE: ${{ matrix.arch }}-${{ matrix.platform }}
      OPTIMIZE_MODE: ${{ matrix.optimize }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup zig
        uses: mlugg/setup-zig@v2

      - name: Install xwin
        if: ${{ matrix.platform == 'windows-msvc' }}
        run: |
          brew update
          brew install xwin

      - name: Build and pack
        run: ./.github/workflows/build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TARGET_TRIPLE }}-${{ matrix.optimize }}
          path: gnuplot-${{ env.TARGET_TRIPLE }}.*
          if-no-files-found: error
