name: Format
on: [push, pull_request]
permissions:
  contents: read
jobs:
  fmt:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup zig
        uses: mlugg/setup-zig@v2
        with:
          version: master

      - name: Check formatting
        run: |
          shopt -s globstar
          zig fmt --check **/*.{zig,zon}
